[pytest]
addopts = -ra --tb=short --alluredir=allure-results --reruns 1 --reruns-delay 2
testpaths = tests
markers =
    smoke: quick sanity checks
    account: registration/login/logout/account management
    cart: shopping cart behaviour
    checkout: checkout & order placement
    products: product listing/search/detail/category/brand
    misc: contact us, subscription, scroll, static pages
base_url = https://www.automationexercise.com
